---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
  server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Основная конфигурация для статических файлов
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Обработка ошибок
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # Проксирование запросов к бэкенду
    location ~ ^/(categories|products|auth|metrics|orders)/ {
        proxy_pass http://backend:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Статус сервера
    location /stub_status {
        allow 127.0.0.1;  
        deny all;         
        stub_status on;   
    }

    # Добавление заголовков для кэширования
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    } 
  } 