imageName: momo-frontend
prometheus_exporter: nginx/nginx-prometheus-exporter:1.4
annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9113"
  prometheus.io/scrape: "true"
replicas: 1
port: 80
environment: production
strategy:
  type: Recreate
resources:
  requests:
    memory: 100Mi
    cpu: 25m
app:
  host: backend
  port: 8081