stages:
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

release:
  stage: release
  image: alpine/helm:3.16.2
  before_script:
    - apk add gettext bash curl
    - cd infra/helm
    - envsubst < Chart.yaml > Chart_substituted.yaml
    - envsubst < templates/secrets.yaml > templates/secrets_substituted.yaml
    - envsubst < charts/backend/Chart.yaml > charts/backend/Chart_substituted.yaml
    - envsubst < charts/frontend/Chart.yaml > charts/frontend/Chart_substituted.yaml
    - envsubst < charts/ingress/Chart.yaml > charts/ingress/Chart_substituted.yaml
    - mv Chart_substituted.yaml Chart.yaml
    - mv templates/secrets_substituted.yaml templates/secrets.yaml
    - mv charts/backend/Chart_substituted.yaml charts/backend/Chart.yaml
    - mv charts/frontend/Chart_substituted.yaml  charts/frontend/Chart.yaml
    - mv charts/ingress/Chart_substituted.yaml  charts/ingress/Chart.yaml
    - helm lint .
    - helm package --dependency-update .
  script:
    - "curl -u \"$NEXUS_REPO_USER:$NEXUS_REPO_PASS\" --upload-file \"/builds/std-030-18/diplom/infra/helm/momo-store-$VERSION.tgz\" \"$NEXUS_REPO_URL/repository/$NEXUS_REPO_HELM/momo-store-$VERSION.tgz\" -v"

deploy-to-k8s:
  stage: deploy
  image: alpine/helm:3.16.2
  before_script:
    - apk add jq
    - cd infra/helm
    - mkdir -p .kube
    - echo "$KUBECONF" | base64 -d > .kube/config
    - export KUBECONFIG=.kube/config
    - chmod 600 .kube/config
  script:
    - helm repo add nexus "$NEXUS_REPO_URL/repository/$NEXUS_REPO_HELM/" --username "$NEXUS_REPO_USER" --password "$NEXUS_REPO_PASS"
    - helm repo update
    - helm search repo nexus
    - helm upgrade --dependency-update --install --atomic -n momo-store --debug --create-namespace momo-store nexus/momo-store --set backend.image.tag=$BACKEND --set frontend.image.tag=$FRONTEND 
    - rm .kube/config
  when:
    manual